[ENH] Min-to-min and max-to-max phase shifting
neurodsp-tools/neurodsp pull request #247
Opened 2021-02-03 21:56 UTC by ryanhammonds

This expands phase shifting to allow for minima-to-minima and maxima-to-maxima sims. It also add phase shifting to `sim_bursty_oscillation`, which wasn't possible before. The `phase` kwarg was added to `sim_cycle` so phase shifting could be done before tiling.

The motivation for this was working with sims + bycycle and the lack of a convenient way to sim cycles from trough-to-trough or peak-to-peak. When simulating from zerox-to-zerox, but bycycle defined cycles otherwise, cyclepoints could get messy. Maybe bycycle could be updated to define cycles from zerox-to-zerox, but that will likely have other side-effects to work out.

The `phase` argument still accepts a float from [0, 1], but it also accepts ``min`` or ``max`` strings to automatically determine the phase shift required to sim from trough-to-trough or peak-to-peak. I'm not sure a mixed param type is the best design so I'm open to suggestions.

Simple example:
```python
import numpy as np

from neurodsp.sim.cycles import sim_cycle
from neurodsp.plts import plot_time_series

n_seconds = 5
fs = 1000

sig_max = sim_cycle(n_seconds, fs, 'asine', phase='max', rdsym=0.75)
sig_min = sim_cycle(n_seconds, fs, 'asine', phase='min', rdsym=0.75)

times = np.arange(0, len(sig_max)/fs, 1/fs)

plot_time_series(times, [sig_min, sig_max], labels=['min', 'max'])
```

Bycycle cyclepoints example:

```python
import numpy as np

from neurodsp.sim import sim_combined
from neurodsp.plts import plot_time_series

from bycycle.features import compute_cyclepoints
from bycycle.plts import plot_cyclepoints_df

np.random.seed(0)

n_seconds = 5
fs = 1000

components = {'sim_bursty_oscillation': {'freq': 10, 'cycle': 'asine',
                                         'rdsym': 0.25, 'phase': 'min'},
              'sim_powerlaw':{'exponent': -2}}

sig = sim_combined(n_seconds, fs, components)

times = np.arange(0, len(sig)/fs, 1/fs)

df_samples = compute_cyclepoints(sig, fs, (1, 50))
plot_cyclepoints_df(df_samples, sig, fs)
```

2021-02-05 05:07 UTC, TomDonoghue requested changes

2021-02-05 05:07 UTC, TomDonoghue commented on neurodsp/sim/cycles.py
> +    shift : float or str
I think this this is a couple str options, and not any string, it should probably be
`shift : float or {'min', 'max'}`

I'm not 100% sure if that is the right convention, but it makes sense to me. If so this should be updated across all shift or phase argument descriptions.

2021-02-05 05:07 UTC, TomDonoghue commented on neurodsp/sim/cycles.py
> +        to shift the cycle start start/end on minima or maxima.
you're pulling a Tom by writing `start start` here :)

2021-02-05 05:07 UTC, TomDonoghue commented on neurodsp/sim/periodic.py
> +        be passed to adjust the phase to start/end cycles on either minima (``min``) or
Nitpick, but lines 32-33 are slightly differently described than what should probably be same description as in `sim_cycle` 267-268. 
I would check through and make sure anything that should be the same is the same. 
I might suggest something like:
```
If a number, the shift is defined as a relative proportion of cycle, between [0, 1]. 
If 'min' or 'max', the cycle is shifted to start at it's minima or maxima. 
```

2021-02-05 05:19 UTC, TomDonoghue commented
This looks like a really nice extension, thanks @ryanhammonds!

I think all the extended functionality makes sense / looks good here! I don't love the mixed input type of the `phase` arg, but I can't really think of any other clear / obvious way to do it, so I reckon this should be fine. I've made some comments, mostly on documentation stuff, if you want to check through and push any updates (if you agree with them).

2021-02-05 05:22 UTC, TomDonoghue commented on neurodsp/utils/checks.py
> +    param : float, int, or str
Revisiting this just to note that based how things are passed into this function, there has to be a type check before passing anyways - which I think is consistent with the notion that a new checker function should be added, called say `check_param_options` (or something) which checks a parameter value is within a specified list of discrete options.

2021-02-05 05:48 UTC, ryanhammonds commented on neurodsp/sim/cycles.py
> +        If non-zero, applies a phase shift to the oscillation by rotating the cycle.
Thanks! I don't know why I thought a single cycle could also be an oscillation but it makes that it needs 2+.

2021-02-05 05:52 UTC, ryanhammonds commented on neurodsp/utils/checks.py
> +    param : float, int, or str
I'll split this into two separate functions. I've noticed I've been writing a lot of mixed type input params lately which is poor design.

2021-02-22 20:37 UTC, TomDonoghue approved these changes

2021-02-22 20:41 UTC, TomDonoghue commented
Thanks @ryanhammonds for the update! I direct pushed some small spelling / description tweaks. 

This looks good to me - merging in!

2021-02-22 20:41 UTC, merged