[ENH] Simulate spikes / action potentials
neurodsp-tools/neurodsp pull request #259
Opened 2021-04-20 00:01 UTC by ryanhammonds

This adds action potential cycles as the sum of two inverted asymmetrical gaussians:

```python
import matplotlib.pyplot as plt
import numpy as np
from neurodsp.sim.cycles import sim_ap_cycle

n_seconds = 1
fs = 1000

cycle_params = {'centers': (.25, .5), 'stds':(.25, .2),
                'alphas':(8, .2), 'heights': (15, 2.5)}

cyc = sim_ap_cycle(n_seconds, fs, **cycle_params)

times = np.linspace(-1, 1, fs)

plt.plot(times, cyc)
```
![ap_cycle](https://user-images.githubusercontent.com/34786005/115317653-e0fb4d80-a130-11eb-8a85-7bf410546dfa.png)

2021-04-20 02:46 UTC, ryanhammonds commented
This func can be used with scipys curve_fit to fit  segmented APs from real data (bycycle-tools/bycycle#100). The resulting 6 params could be useful (i.e. dimensionality reduction for APs) and included in df_features returned from bycycle.Spikes.fit().
![ap_cycle_fit](https://user-images.githubusercontent.com/34786005/115329862-caacbc00-a147-11eb-802c-9ad0874e2ed7.png)

2021-04-22 14:36 UTC, TomDonoghue requested changes

2021-04-22 14:36 UTC, TomDonoghue commented on neurodsp/sim/cycles.py
> +def sim_skewed_gaussian_cycle(n_seconds, fs, center, std, alpha, height=1):
The parameter `alpha` isn't described in the docstring

2021-04-22 14:42 UTC, TomDonoghue commented on neurodsp/sim/cycles.py
> +        The center of the gaussian.
This definition isn't super clear (it's not obvious if it's about x or y axis), and I think the description in `sim_skewed_gaussian` is clearer and could be copied here.

2021-04-22 15:02 UTC, TomDonoghue commented
This looks super cool! 

I had a quick scan of the code, left a coupe comments, and here's a couple quick "higher-level" questions:
- It's not clear to me that the AP sim is a _cycle_, per se. Would it fit better in `sim.transients`?
- I presume changing the gaussian code to not use scipy is about getting more control over height, center, etc? Setting `height` feels like it overlaps with normalizing the signal, and `center` feels a little weird to have in the cycles, because it makes looks like it 'cuts off' the edge of a gaussian? Am I right in thinking that one would probably never want to set `center` to a custom value because it would create weird concatenation artifacts? 

Between the two comments, I think it's possible it might be a cleaner split to put some stuff in transients, that might work well for generating APs, but might not be quite the same as what one wants for a cycle? What do you think?

2021-04-22 19:47 UTC, ryanhammonds commented
Thanks for the review!

- I think it makes sense to refactor into `transients` with an alias in `cycles` so it can still be used with sim_bursty_oscillation.
- The main reason for the sim_gaussian_cycle changes was to have control over the cycle center, which is important only for skewed cycles. Here's an example of how center makes a difference with skewed cycles:

![skew_center](https://user-images.githubusercontent.com/34786005/115774615-a8dd5000-a366-11eb-871c-c57537589361.png)

The `height` param is a bit different from `variance`. I'm not sure there is a clear mapping between these params.
![variance_v_height](https://user-images.githubusercontent.com/34786005/115774516-8b0feb00-a366-11eb-83fb-5151b4d17929.png)

2021-04-27 03:32 UTC, ryanhammonds commented
I've update the code here based on the review. I also update the ap func to take iterables for simulation parameters. This is because 3 gaussians may desired in some cases (i.e. the sum of conductive, sodium and potassium currents).

```python
from neurodsp.sim.cycles import sim_ap_cycle
import matplotlib.pyplot as plt

cycle = sim_ap_cycle(1, 100, (.5, .3, .6), (.1, .1, .1), (0, -1, 1), (-5, 1, 2.5))

plt.plot(cycle)
```
![example_double_skew](https://user-images.githubusercontent.com/34786005/116180722-3fdf3a80-a6ce-11eb-8dd5-de2702a9dd60.png)

2021-05-27 19:04 UTC, ryanhammonds commented
@TomDonoghue I made a final round of updates. There have been several changes since the last time you reviewed, but it should be ready to merge. Let me know if you'd like to look over the changes, otherwise I'll merge.

2021-06-03 14:48 UTC, TomDonoghue approved these changes

2021-06-03 17:46 UTC, merged